<a href="https://colab.research.google.com/github/poudyaldiksha/Data-Science-project/blob/main/AssignmentOct21_b2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 1

### Activity 1: Multiplying numbers of the list

Create a list which contains some numbers and multiply all the numbers in the list.

**Constraint:** The list should not be empty.

For Example:

```
list[1,2,3] will give '6'
list[2,3,7] will give '42'
```


In [ ]:
import numpy
list1 = [1, 2, 3]
list2 = [2, 3, 7]

# using numpy.prod() to get the multiplications
result1 = numpy.prod(list1)
result2 = numpy.prod(list2)
print(result1)
print(result2)


6
42


### Activity 2: Change Dimension of an Array and Convert the NumPy Array into a List

Write a program to change the dimension of an array (say `my_arr =[1, 2, 3, 4, 5, 6, 7, 8, 9]`) into a 3 X 3 (3 rows and 3 columns) array and convert this NumPy array into a list.

**For Example:**
```
Original array is [1 2 3 4 5 6 7 8 9]
Dimension is (9,)
Change array shape to (3, 3) -> 3 rows and 3 columns
[[1 2 3]
 [4 5 6]
 [7 8 9]]```

The data type of the converted variable is
 list

In [ ]:
import numpy as np

def main():
    # initializing array
    result = np.arange(1, 10)
    print('Initialized array:')
    print(result)

    # resized array with dimensions in
    # range of original array
    result1 = np.resize(result, (3, 3))
    print('3x3 array:')
    print(result1)

if __name__ == "__main__":
    main()


Initialized array:
[1 2 3 4 5 6 7 8 9]
3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Activity 3: Find Square Root and Calculate the value of $c$

Write a program to perform following two tasks:
-  Print the square root of numbers in the list.
- Compute the value of $c$ in the equation $c=\sqrt(a^2 + b^2)$.

**For Example**:

```
list1 = [4, 16, 9, 1, 25]
 output: [2   4    3   1    5 ]


If a= 30
   b= 42
The value of c =  51.61395160225576
```



In [ ]:
import numpy as geek

# applying sqrt() method on integer numbers

array1 = geek.sqrt([4, 16, 9, 1 , 25])

print("squareroot of an array1 : ", array1)




squareroot of an array1 :  [2. 4. 3. 1. 5.]


### Activity 4: Populate a Number List

Write a program that populates a list by numbers that lies in the range of 0 - 49 and also divisible by 5. Use List Comprehension method.

**Output**: `[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]`


In [ ]:
divisible_by_5 = [num for num in range(50) if num % 5 == 0]
print(divisible_by_5)



[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]


### Activity 5: Convert Fahrenheit into Celsius

Write a program to convert the values in Fahrenheit degrees into Celsius degrees.

**Formula**:

```
celsius = (fahrenheit - 32) / 1.8
```

**Example**:

```
Values in Fahrenheit degrees:
[ 0  32   45.21]
Values in Celsius degrees:
[-17.78   0  7.34]
```




In [ ]:
def fahrenheit_to_celsius(fahrenheit):
    celsius = (fahrenheit - 32) / 1.8
    return celsius

# Example usage
fahrenheit = float(input("Enter temperature in Fahrenheit: "))
celsius = fahrenheit_to_celsius(fahrenheit)
print(f"The temperature in Celsius is {celsius:.2f}°C")

Enter temperature in Fahrenheit: 45.21
The temperature in Celsius is 7.34°C


### Activity 6: Array containing Random Integers

Create an array containing 40 random integers between 200 and 245 and  Print

In [ ]:
import numpy as np

# Creating an array of 40 random integers between 200 and 245
random_integers = np.random.randint(200, 246, 40)

# Printing the array
print(random_integers)


[212 230 221 208 244 221 226 204 201 239 230 228 217 208 219 234 232 216
 217 244 220 200 221 213 239 200 213 240 238 214 230 244 200 240 207 219
 212 214 228 212]


#### Activity 6.2: Calculate Mean and Median

Calculate the mean value and median value of the above Array.

In [ ]:
import numpy

speed = [212,230,221,208,244,221,226,204,201,239,230,228,217,208,219,234,232,216,217,244,220,200,221,213,239,200,213,240,238,214,230,244,200,240,207,219,212,214,228,212]

x = numpy.mean(speed)

print(x)

import numpy

speed = [212,230,221,208,244,221,226,204,201,239,230,228,217,208,219,234,232,216,217,244,220,200,221,213,239,200,213,240,238,214,230,244,200,240,207,219,212,214,228,212]

x = numpy.median(speed)

print(x)


221.375
219.5


---

#### Activity 6.3: Find Minimum and Maximum

Find the minimum and maximum value in the above Array.

In [ ]:
# import necessary libraries
import pandas as pd
import numpy as np

# defining series
my_series = pd.Series([212,230,221,208,244,221,226,204,201,239,230,228,217,208,219,234,232,216,217,244,220,200,221,213,239,200,213,240,238,214,230,244,200,240,207,219,212,214,228,212])

# using np.max() method
max_val = np.max(my_series)

# printing result
print(max_val)

# importing necessary libraries
import pandas as pd
import numpy as np

# defining your series
my_series = pd.Series([212,230,221,208,244,221,226,204,201,239,230,228,217,208,219,234,232,216,217,244,220,200,221,213,239,200,213,240,238,214,230,244,200,240,207,219,212,214,228,212])

# using np.max() method
max_val = np.min(my_series)

# printing result
print(max_val)


244
200


---

#### Activity 6.4: Arrange in Descending Order

Arrange the values in descending order

In [ ]:
# a list of numbers
my_numbers = [212,230,221,208,244,221,226,204,201,239,230,228,217,208,219,234,232,216,217,244,220,200,221,213,239,200,213,240,238,214,230,244,200,240,207,219,212,214,228,212]

#sorting list in-place in descending order
my_numbers.sort(reverse=True)

#printing modified list
print(my_numbers)


[244, 244, 244, 240, 240, 239, 239, 238, 234, 232, 230, 230, 230, 228, 228, 226, 221, 221, 221, 220, 219, 219, 217, 217, 216, 214, 214, 213, 213, 212, 212, 212, 208, 208, 207, 204, 201, 200, 200, 200]


---

### Activity 7: Find whether Two Lines are Parallel

Given two lines, determine whether they are parallel or not.
Lines are represented using a list [a, b, c] which corresponds to the straight line $ax+by=c$.



**Hints:**
- Two lines are parallel if their slopes are equal.

- A line in the form of $ax+by=c$ has slope $\frac {-a}{b}$.
- Ignore the minus $(-)$ sign. Just calculate $\frac {a}{b}$ for both lines and find out whether they are equal or not.


**Example:**
```
line1 = [2,3,4]
line2 = [4,6,8]

Are lines parallel?
True
```


In [ ]:
def are_parallel(line1, line2):
    # Extracting coefficients
    a1, b1, _ = line1
    a2, b2, _ = line2

    # Avoiding division by zero for vertical lines
    if b1 == 0 and b2 == 0:
        return True  # Both lines are vertical, hence parallel
    if b1 == 0 or b2 == 0:
        return False  # One line is vertical, the other isn't

    # Checking if the slopes (a/b) are equal
    return a1 * b2 == a2 * b1

# Example lines
line1 = [2, 3, 4]  # 2x + 3y = 5
line2 = [4, 6, 8]  # 4x + 6y = 7

# Checking if they are parallel
if are_parallel(line1, line2):
    print("The lines are parallel.")
else:
    print("The lines are not parallel.")



The lines are parallel.
