<a href="https://colab.research.google.com/github/poudyaldiksha/Data-Science-project/blob/main/Lesson_8_b2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lesson 8: Numpy arrays -III

#### Activity 1: Copying Arrays

When working with NumPy arrays, sometimes you might need to create a copy of an array to prevent changes to the original array. Here are a few ways to do that:
- Assignment (No Copy)
- Shallow Copy using `view()`
- Deep Copy using `copy()`

**1. Assignment (No Copy)**

Assigning one array to another does not create a copy; it creates a reference to the same array. Any modifications to the new array will also affect the original array.




In [ ]:
# activity: Make a copy by assignment
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = arr1
print("original arr", arr1)
print("assigned arr",arr2)

arr2[2] = 23

print("\nafter modification\n")

print("original arr", arr1)
print("assigned arr",arr2)



original arr [1 2 3 4 5]
assigned arr [1 2 3 4 5]

after modification

original arr [ 1  2 23  4  5]
assigned arr [ 1  2 23  4  5]


**2. Shallow Copy using `view()`**

Shallow Copy creates a new array object that looks at the same data. Changes to the data in the view will affect the original array and vice versa.

When you create a shallow copy of a NumPy array using `view()`, you're essentially creating a new array object that shares the same underlying data with the original array. This means that both arrays refer to the same data buffer in memory.



In [ ]:
# Activity: Copying using view()
arr1 = np.array([1,2,3,4,5])
arr2 = arr1.view()
print("original arr", arr1)
print("shallow copyarr",arr2)

arr2[2] = 23

print("\nafter modification\n")

print("original arr", arr1)
print("shallow copy  arr",arr2)


original arr [1 2 3 4 5]
shallow copyarr [1 2 3 4 5]

after modification

original arr [ 1  2 23  4  5]
shallow copy  arr [ 1  2 23  4  5]


**3. Deep Copy using `copy()`**

A deep copy creates a new array with a new data buffer. Changes to the new array will not affect the original array and vice versa.

In [ ]:
#Activity: Copying using copy()
arr1 = np.array([1,2,3,4,5])
arr2 = arr1.copy()
print("original arr", arr1)
print(" copyarr",arr2)

arr2[2] = 23

print("\nafter modification\n")

print("original arr", arr1)
print("copy  arr",arr2)


original arr [1 2 3 4 5]
 copyarr [1 2 3 4 5]

after modification

original arr [1 2 3 4 5]
copy  arr [ 1  2 23  4  5]


 In shallow copy , a copy of the original object is stored and only the reference address is finally copied.

 In deep copy, the copy of the original object and the repetitive copies both are stored.

#### Activity 2: Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called `sort( )`, that will sort a specified array.

In [ ]:
# Activity:

arr_15= np.array([-1/2,-1/4,2,0,1])
print(np.sort(arr_15)[::-1])


[ 2.    1.    0.   -0.25 -0.5 ]


In [ ]:
arr_16 = np.array([1,55,77,22,99])
arr_2 = np.sort(arr_16)

arr_2[2] = 23

print("\nafter modification\n")

print("original arr", arr_16)
print("copy  arr",arr_2)



after modification

original arr [ 1 55 77 22 99]
copy  arr [ 1 22 23 77 99]


**Note:** This method returns a copy of the array, leaving the original array unchanged.

#### Activity 3: Array Length
The length of an array (or array length) is:

- The number of items in a one-dimensional array.

- The number of rows in a two-dimensional array.

- The number of blocks in a three-dimensional array.

To calculate the length of a NumPy array, you can use the `len()` function.




In [ ]:
one_dim_arr = np.arange(1,25)
one_dim_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(1,29).reshape(2,14)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [ ]:
np.arange(1,31).reshape(3,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [ ]:
#Create a NumPy array for all the three different dimensions and calculate their lengths.
one_dim_arr = np.arange(1,25) # 24
two_dim_arr = np.arange(1,29).reshape(2,14) #2
three_dim_arr = np.arange(1,31).reshape(3,2,5) #3
print(len(one_dim_arr))
print(len(two_dim_arr))
print((len(three_dim_arr)))

24
2
3


**Note:**  

 The `len()` function gives different outputs for multi-dimensional NumPy arrays.

#### Activity 4: The `size` Keyword

To find the number of items in a NumPy array, you can use the `size` keyword. Regardless of dimensions, the `size` keyword will always return the number of items in a NumPy array.

In [ ]:
# Compute the number of items in the above created NumPy arrays.
print(one_dim_arr.size)
print(two_dim_arr.size)
print(three_dim_arr.size)

24
28
30


#### Activity 5: Descriptive Statistics

Using NumPy arrays, we can easily do some statistical calculations.

Consider that  you are a laptop retailer and you have a few laptops in your inventory.

|Laptop Model|Price (INR)|# Units Available|
|-|-|-|
|Dell Inspiron 15|	45000|	15|
HP Pavilion 14| 55000| 12|
Lenovo ThinkPad X1| 65000| 10|
MacBook Air| 120000| 8|
Asus ZenBook| 75000| 6|
Acer Swift 3| 45000| 18|
Microsoft Surface Laptop| 85000| 9|
Razer Blade Stealth| 60000| 11|
Samsung Galaxy Book| 70000| 7|
Google Pixelbook Go| 80000| 5|

Suppose you decided to do some analysis of your inventory. In the process, you want to find answers to the following questions:

1. What is the total revenue generated from laptop sales?

2. What is the average price of a laptop?

3. What is the price of the cheapest laptop in the inventory?

4. What is the price of the most expensive laptop in the inventory?

5. What is the median price of a laptop?

6. What is the most commonly occurring price of a laptop?

You can answer all these questions in a few seconds by creating NumPy arrays and by applying the `sum(), mean(), median(), min()` and `max()` functions.


```
laptop_models = ['Dell Inspiron', 'HP Pavilion', 'Lenovo ThinkPad', 'Apple MacBook Pro', 'Asus ZenBook',
                 'Acer Swift', 'Microsoft Surface', 'Razer Blade Stealth', 'Samsung Galaxy Book', 'Google Pixelbook Go]
prices = [45000, 55000, 65000, 120000, 75000, 45000, 85000, 60000, 70000, 80000]
units_sold = [15, 12, 10, 8, 6, 18, 9, 11, 7, 5]
```

In [ ]:
#Create Arrays
# Define lists for laptop data
laptop_models = ['Dell Inspiron', 'HP Pavilion', 'Lenovo ThinkPad', 'Apple MacBook Pro', 'Asus ZenBook',
                 'Acer Swift', 'Microsoft Surface', 'Razer Blade Stealth', 'Samsung Galaxy Book', 'Google Pixelbook Go']
prices = [45000, 55000, 65000, 120000, 75000, 45000, 85000, 60000, 70000, 80000]
units_sold = [15, 12, 10, 8, 6, 18, 9, 11, 7, 5]

# Convert lists to NumPy arrays
price_array = np.array(prices)
units_sold_array =np.array(units_sold)


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)
total = np.sum(a * b)
total

[ 4 10 18]


32

In [ ]:
#Calculate Total Revenue
total_price_for_each_laptop = price_array * units_sold_array
print(total_price_for_each_laptop)

total_revenue = np.sum(total_price_for_each_laptop)
print("total revenue:",total_revenue)


[675000 660000 650000 960000 450000 810000 765000 660000 490000 400000]
total revenue: 6520000


In [ ]:
# Calculate Average price
np.mean(price_array)


70000.0

In [ ]:
#Find Cheapest and Most Expensive Laptop Prices
print("expensive laptop:",np.max(price_array))
print("cheap",np.min(price_array))

expensive laptop: 120000
cheap 45000


In [ ]:
#Calculate Median Price
np.median(price_array)

67500.0

The value which occurs the most number of times is called the **modal** value or simply **mode**.

Unfortunately, the `numpy` module does not have a function to calculate the modal value. So, either we can create our own function which is a very complicated process or we can use the `mode()` function from the `scipy` library.


In the `scipy` library, there is a module called `stats` which contains the `mode()` function. So we have to import the `stats` module from the `scipy` library.

In [ ]:
# Compute the modal value using the 'mode()' function from the 'scipy.stats' module.
from scipy import stats
stats.mode(prices)


ModeResult(mode=45000, count=2)



**Note:** `from library_name import module_name` is another way of importing a module. It is also a standard practice.

NumPy and SciPy are separate libraries, but often used together for scientific computing tasks. Here's how you can import specific modules or functions from NumPy:

1. **Importing NumPy Alone:**

```
import numpy as np
```
This imports the entire NumPy library under the alias np, allowing you to access all its functions and modules using `np.<function>` or `np.<module>.<function>`.

2. **Importing Specific Functions:**

```
from numpy import array, linspace

```
This imports only the `array()` and `linspace()` functions from NumPy. You can use them directly without prefixing with np.

3. **Importing Submodules:**

```
from numpy import random
```
This imports the random submodule from NumPy, allowing you to use functions like `random.randint()` directly.



#### **SciPy and NumPy**

SciPy builds on top of NumPy and provides additional functionality for scientific and technical computing. It includes modules for optimization, integration, interpolation, and much more.

Using Together: While you can use NumPy alone for basic array operations and mathematical functions, SciPy extends this by adding advanced algorithms and tools. Importing SciPy typically involves importing specific modules or functions as needed, similar to NumPy.

####Activity 6: Mathematical Operations On A NumPy Array

Performing mathematical operations on a NumPy array is easier compared to a Python list.



In [ ]:
#With radii of 15 circles,compute the area of every circle.

import random
radii = [ random.randint(1,10) for i in range(0,15)] # list comprehension method
print(radii)




[7, 5, 2, 3, 2, 1, 6, 9, 2, 8, 8, 5, 1, 6, 8]


In [ ]:
np_rad = np.array(radii)
area_circles  = np.pi * (np_rad ** 2)
area_circles


array([153.93804003,  78.53981634,  12.56637061,  28.27433388,
        12.56637061,   3.14159265, 113.09733553, 254.46900494,
        12.56637061, 201.06192983, 201.06192983,  78.53981634,
         3.14159265, 113.09733553, 201.06192983])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array(random.randint(1,10))

array(5)

In [ ]:
t = np.array([random.randint(1,10) for i in range(1,16)])
t

array([ 9,  7,  8,  6,  7, 10,  4,  8,  1,  5,  5,  8,  5,  3,  9])

In [ ]:
w = np.array((1,2,3))
w

array([1, 2, 3])

In [ ]:
d = (1,2,3)
type(d)

tuple

Now, using the same approach, you create two NumPy arrays: one having radii (numbers from `5` to `15`) of `10` cylinders and another having their corresponding heights (numbers from `20` to `30`).

**Note:** The volume of a cylinder is
$\pi r^{2}h$
, where
$h$
is height of the cylinder and
$r$
is the radius of the cylinder.

In [ ]:
# Create two NumPy arrays. One having a radii of 10 cylinders and another having their corresponding heights.
# Compute the volume of the 10 cylinders by multiplying the NumPy arrays and store the new NumPy array in the new variable.

cyc_radii = np.arange(5,15)
cyc_heights = np.arange(21,31)
cyc_volume = np.pi *(cyc_radii ** 2)* cyc_heights
cyc_volume

array([ 1649.33614313,  2488.14138164,  3540.5749206 ,  4825.48631591,
        6361.72512352,  8168.14089933, 10263.58319928, 12666.90157927,
       15396.94559524, 18472.56480311])

#### Activity 7:Random Numbers: `random()`

Random number generation is a crucial part of simulations, statistical analysis, and machine learning. NumPy provides several functions to generate random numbers:

`random():` Generates random floats in the half-open interval [0.0, 1.0).

In [ ]:
# Create a random float value in between 0 and 1

np.random.random()

0.6834905628457413

In [ ]:
# Create 2d random array  in between 0 and 1
np.random.random((3,3))

array([[0.84574695, 0.47455748, 0.94623725],
       [0.41920685, 0.4574043 , 0.91878141],
       [0.69040698, 0.52056293, 0.29869182]])

In [ ]:
# Generate a  3d random float between 0 and 1
random_floats = np.random.random((2,3,2))
print("Random floats:", random_floats)

Random floats: [[[0.64665643 0.34185728]
  [0.93332663 0.36611159]
  [0.82811275 0.88594847]]

 [[0.53919727 0.1497775 ]
  [0.53268819 0.89695101]
  [0.88206585 0.27456677]]]


### Activity 8: Random Numbers: `rand()`
`numpy.rand():` Generates an array of specified shape with random floats in the half-open interval [0.0, 1.0).

In [ ]:
# create 1d array of 3 element
np.random.rand()

0.6252711127789757

In [ ]:
# Generate a 3x2 array of random floats
np.random.rand(3,2)

array([[0.24213486, 0.36553877],
       [0.09625382, 0.67448575],
       [0.63459276, 0.04957829]])

In [ ]:
# Generate a 2x3x2 array of random floats
random_array = np.random.rand(2,3,2)
print("Random array:\n", random_array)

Random array:
 [[[0.73990988 0.67244684]
  [0.3846179  0.29531674]
  [0.47419445 0.03148758]]

 [[0.28646684 0.11064624]
  [0.67939882 0.07827155]
  [0.84560945 0.87013399]]]


### Activity 9: Random Numbers: `randint()`
`numpy.randint():` Generates random integers from a low (inclusive) to high (exclusive) range.



In [ ]:
# Generate a random integer between 1 and 10
a = np.random.randint(1,10)
type(a)

int

In [ ]:
# Generate 5 random integers between 1 and 10
np.random.randint(1,10,5)

array([1, 9, 7, 5, 8])

In [ ]:
# Create 2d random array  in between 1 and 4
np.random.randint(1,10,(4,4))

array([[6, 4, 7, 4],
       [8, 4, 6, 8],
       [8, 9, 2, 4],
       [5, 1, 5, 1]])


`np.random.seed()` is a NumPy function that initializes the random number generator with a seed value . In the context of random number generation:

- Random Number Generator (RNG) Initialization: Setting a seed with np.random.seed() ensures that the random numbers generated by NumPy's random module are reproducible.
-  That means, if you use the same seed value before generating random numbers, you will get the same sequence of random numbers every time.

In [ ]:
# Create 3d array with randaom values between 1 and 4 with seed value as 10
np.random.seed(10)
np.random.randint(1,10,(4,4))

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1],
       [5, 7, 9, 2]])

In [ ]:
np.random.randint(1,10,(4,4))

array([[9, 5, 2, 4],
       [7, 6, 4, 7],
       [2, 5, 3, 7],
       [8, 9, 9, 3]])

In [ ]:
2**32 - 1

4294967295

In [ ]:
np.random.seed(4294967295)
np.random.randint(1,10,(4,4))

array([[4, 3, 8, 5],
       [1, 7, 1, 3],
       [7, 8, 8, 7],
       [6, 5, 1, 8]])

If you run the  code with `np.random.seed(10)` set, you'll get the same arrays every time you run the code subsequently.

### Activity 10: Random Numbers: `choice()`
`numpy.random.choice():`Generates a random sample from a given 1-D array.

In [ ]:
# Generates a random sample from a given 1-D array.
list_1= [10, 20, 30, 40, 50]
array_1 = np.array(list_1)
random_sample = np.random.choice(array_1, size = 2)
print("Random sample from array:", random_sample)
type(random_sample)

Random sample from array: [40 50]


numpy.ndarray

In [ ]:
list_1= [10, 20, 30, 40, 50]

random_sample = np.random.choice(list_1, size = 2)
print("Random sample from array:", random_sample)
type(random_sample)

Random sample from array: [40 20]


numpy.ndarray

### Activity 11: Random Numbers: `shuffle()`


In [ ]:
# Shuffle
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
np.random.shuffle(data)
print("Shuffled data:\n", data)

Shuffled data:
 [[ 9 10]
 [ 5  6]
 [ 7  8]
 [ 1  2]
 [ 3  4]]


###Activity 12: `reshape()`,` ravel()`,` flatten()`

In [ ]:
# Activity: Reshape()
array_1 = np.arange(1,10).reshape(3,3)
array_1

In [ ]:
# Activity: Ravel()
arr_ravel = array_1.ravel()
arr_ravel

In [ ]:
#Activity: Flatten()
arr_flatten = array_1.flatten()
arr_flatten

The ravel() and flatten() functions in NumPy both return a flattened array, but they have some key differences in terms of how they handle memory:

`ravel()`

- Returns a flattened array.
- Returns a view whenever possible: This means that ravel() tries to avoid creating a new array if it can. If the array is already contiguous in memory, it will return a view of the original array. If it can't return a view, it will return a copy.
- Changes to the raveled array may affect the original array if it returns a view.

`flatten()`

- Returns a flattened array.
- Always returns a copy: This means that flatten() creates a new array and the changes to the flattened array will not affect the original array.
- Does not affect the original array: Since it returns a copy, any modifications to the flattened array will not impact the original array.

In [ ]:
# Create a 2x2 array
arr = np.array([[1, 2],
                [3, 4]])

# Use ravel() to flatten the array
raveled_arr = arr.ravel()
print("Raveled array:", raveled_arr)

# Modify the raveled array
raveled_arr[0] = 10
print("Modified raveled array:", raveled_arr)
print("Original array after ravel modification:", arr)



In [ ]:
# Create a 2x2 array
arr = np.array([[1, 2],
                [3, 4]])

# Use flatten() to flatten the array
flattened_arr = arr.flatten()
print("Flattened array:", flattened_arr)

# Modify the flattened array
flattened_arr[0] = 20
print("Modified flattened array:", flattened_arr)
print("Original array after flatten modification:", arr)

In [ ]:
# Create a 2x3 array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# C order (default)
c_order = np.ravel(arr, order='C')
print("C order:", c_order)

# F order
f_order = np.ravel(arr, order='F')
print("F order:", f_order)

C Order: [1, 2, 3, 4, 5, 6]
- Rows are stored sequentially: first row [1, 2, 3] followed by the second row [4, 5, 6].

F Order: [1, 4, 2, 5, 3, 6]
- Columns are stored sequentially: first column [1, 4], second column [2, 5], and third column [3, 6].

**Practical Use Cases:**

**C Order:**

- Typically used when performing operations that process rows of an array.
- Common in many numerical and scientific computations

**F Order:**

- Useful in linear algebra and matrix operations where column-wise processing is needed.



### Activity 13: Addition of arrays

In [ ]:
# Activity
arr1 = np.arange(1,10).reshape(3,3)
arr1

In [ ]:
arr2 = np.arange(11,20).reshape(3,3)
arr2

In [ ]:
arr1 + arr2

In [ ]:
np.add(arr1,arr2)

In [ ]:
np.subtract(arr1,arr2)

In [ ]:
np.multiply(arr1,arr2)

In [ ]:
np.divide(arr1,arr2)

In [ ]:
# Define two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Add the arrays
result_add = array1 + array2
print("Addition:\n", result_add)

### Activity 14: Subtraction of Arrays

In [ ]:
#Activity


In [ ]:

# Define two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Subtract the arrays
result_subtract = array1 - array2
print("Subtraction:\n", result_subtract)

### Activity 15: Multiplication of Arrays

In [ ]:
# Define two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Multiply the arrays element-wise
result_multiply = array1 * array2
print("Element-wise Multiplication:\n", result_multiply)

### Activity 16: Division of Arrays

In [ ]:
#Activity


In [ ]:

# Define two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Divide the arrays element-wise
result_divide = array1 / array2
print("Element-wise Division:\n", result_divide)

### Activity 17: Array Multiplication (using @ operator)

- The @ operator in Python for numpy arrays is used for matrix multiplication, which is also known as the dot product when applied to 2D arrays (matrices).
- While the dot product of two vectors results in a scalar, the matrix multiplication of two matrices results in another matrix.

Array Multiplication Using @ Operator
In the context of numpy, when you use the @ operator with two 2D arrays (matrices), it performs matrix multiplication.

In [ ]:
# Define two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Dot product using @ operator
dot_product = vector_a @ vector_b

print("Vector A:", vector_a)
print("Vector B:", vector_b)
print("Dot Product:", dot_product)

In [ ]:
# Define two arrays
array1 = np.array([[1, 2], [3, 4], [5, 6]])
array2 = np.array([[7, 8], [9, 10]])

# Matrix multiplication using @ operator
result_matrix_multiplication = array1 @ array2
print("Matrix Multiplication (using @ operator):\n", result_matrix_multiplication)

Step-by-Step Calculation

𝐶
11 = (1 * 11) + (2 * 14) + (3 * 17) = 11 + 28 + 51 = 90

Element

𝐶
12 = (1 * 12) + (2 * 15) + (3 * 18) = 12 + 30 + 54 = 96

Element

𝐶
13 = (1 * 13) + (2 * 16) + (3 * 19)= 13 + 32 + 57 = 102

Element

𝐶
21 =(4 * 11) + (5 * 14) + (6 * 17)= 44 + 70 + 102 = 216

Element

𝐶
22 =(4 * 12)+(5 * 15)+(6 * 18)= 48 +75 + 108 =231


Element

𝐶
23 =(4 * 13)+(5 * 16)+(6 * 19)= 52 + 80 + 114 = 246

Element

𝐶
31 =(7 * 11)+(8 * 14)+(9 * 17)= 77 +112 +153 = 342

Element

𝐶
32 =(7 * 12)+(8 * 15)+(9 * 18)= 84 + 120 +162 = 366

Element

𝐶
33 =(7 * 13)+(8 * 16)+(9 * 19)= 91 + 128 + 171 = 390



### Activity 18: `argmax()` and `argmin()`

- The `argmax()`function in NumPy is used to find the index of the maximum value in an array. It can be used with 1-dimensional arrays to return a single index or with multi-dimensional arrays to return indices along a specified axis.

- The `argmin()`function in NumPy is used to find the index of the minimum value in an array.

**1D Array Example**
For a 1D array, argmax() returns the index of the maximum value.

In [ ]:
# For a 1D array, argmax() returns the index of the maximum value.
arr3 =  np.array([1,3,7,2,5])
np.max(arr3)

In [ ]:
np.argmax(arr3)

In [ ]:
np.argmin(arr3)

**2D Array Example**

For a 2D array, argmax() can be used to find the index of the maximum value along a specified axis.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                 [7, 8, 9]])

# Find the index of the maximum value in the entire array
index_of_max_flat = np.argmax(arr)

# Find the index of the maximum value along each column
index_of_max_axis0 = np.argmax(arr, axis=0)

# Find the index of the maximum value along each row
index_of_max_axis1 = np.argmax(arr, axis=1)

print("Array:")
print(arr)
print("\nIndex of maximum value in the flattened array:", index_of_max_flat)
print("Index of maximum values along axis 0 (columns):", index_of_max_axis0)
print("Index of maximum values along axis 1 (rows):", index_of_max_axis1)

In [ ]:
index_of_max_flat = np.argmax(arr)
index_of_max_flat

In [ ]:
arr.shape

**Multi-Dimensional Array Example**

For higher-dimensional arrays, argmax() can still be applied along specified axes.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]]])

# Find the index of the maximum value in the entire array
index_of_max_flat = np.argmax(arr)

# Find the index of the maximum value along the first axis
index_of_max_axis0 = np.argmax(arr, axis=0)

# Find the index of the maximum value along the second axis
index_of_max_axis1 = np.argmax(arr, axis=1)

print("Array:")
print(arr)
print("\nIndex of maximum value in the flattened array:", index_of_max_flat)
print("Index of maximum values along axis 0:", index_of_max_axis0)
print("Index of maximum values along axis 1:", index_of_max_axis1)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]]])

# Find the index of the maximum value in the entire array
index_of_max_flat = np.argmax(arr)
index_of_max_flat

In [ ]:
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],

               [[7, 8, 9],
               [10, 11, 12]]])
index_of_max_axis0 = np.argmax(arr, axis=0)
index_of_max_axis0

In [ ]:
arr_7 = np.array([[[19, 11, 31],
                 [42, 5, 64]],

               [[7, 80, 9],
               [10, 111, 12]]])
index_of_max_axis0 = np.argmax(arr_7, axis=0)
index_of_max_axis0

In [ ]:
arr_7 = np.array([[[19, 11, 31],
                 [42, 5, 64]],

               [[7, 80, 9],
               [10, 111, 12]]])
index_of_max_axis0 = np.argmax(arr_7, axis=1)
index_of_max_axis0

**Summary**

- np.argmax(array) returns the index of the maximum value in a flattened array.
- np.argmax(array, axis=0) returns the indices of the maximum values along the specified axis 0 (columns).
- np.argmax(array, axis=1) returns the indices of the maximum values along the specified axis 1 (rows).

### Activity 19: Concatenate Two array

In [ ]:
# Concatenate using concatenate() function
np.concatenate((arr1,arr2))

**Row wise concatenate**

In [ ]:
# Activity
np.concatenate((arr1,arr2), axis= 1)

**Column wise concatenate**

In [ ]:
#Activity
np.concatenate((arr1,arr2), axis= 0)

**Concatenate Two array by using Stack function**
`vstack()` and `hstack()` are functions in NumPy used for stacking arrays either vertically or horizontally, respectively.

**`np.vstack()`**

- Function: np.vstack() stacks arrays vertically (row-wise).
- Usage: It takes a sequence of arrays and stacks them vertically to make a single array. The arrays must have the same number of columns (i.e., the same shape along all but the first axis).

In [ ]:
# np.vstack() it will concatenate two array vertically
np.vstack((arr1,arr2))


In [ ]:
#Activity

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

result = np.vstack((arr1, arr2))

print(result)

**`np.hstack()`**

- Function: np.hstack() stacks arrays horizontally (column-wise).
- Usage: It takes a sequence of arrays and stacks them horizontally to make a single array. The arrays must have the same number of rows (i.e., the same shape along all but the second axis).

In [ ]:
# np.hstack() it will concatenate two array horizontally
np.hstack((arr1,arr2))


In [ ]:
#Activity
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.hstack((arr1, arr2))

print(result)